In [1]:
import warnings

# imports
import numpy as np
from keras.layers import Dense
from keras.models import Model, Sequential
from keras.utils import np_utils

warnings.filterwarnings("ignore")

np.random.seed(23)

Using TensorFlow backend.


In [2]:
def fizzbuzz(number):
    if number % 15 == 0:
        return "FizzBuzz"
    elif number % 5 == 0:
        return "Buzz"
    elif number % 3 == 0:
        return "Fizz"
    else:
        return number


[fizzbuzz(i) for i in range(1, 101)]

[1,
 2,
 'Fizz',
 4,
 'Buzz',
 'Fizz',
 7,
 8,
 'Fizz',
 'Buzz',
 11,
 'Fizz',
 13,
 14,
 'FizzBuzz',
 16,
 17,
 'Fizz',
 19,
 'Buzz',
 'Fizz',
 22,
 23,
 'Fizz',
 'Buzz',
 26,
 'Fizz',
 28,
 29,
 'FizzBuzz',
 31,
 32,
 'Fizz',
 34,
 'Buzz',
 'Fizz',
 37,
 38,
 'Fizz',
 'Buzz',
 41,
 'Fizz',
 43,
 44,
 'FizzBuzz',
 46,
 47,
 'Fizz',
 49,
 'Buzz',
 'Fizz',
 52,
 53,
 'Fizz',
 'Buzz',
 56,
 'Fizz',
 58,
 59,
 'FizzBuzz',
 61,
 62,
 'Fizz',
 64,
 'Buzz',
 'Fizz',
 67,
 68,
 'Fizz',
 'Buzz',
 71,
 'Fizz',
 73,
 74,
 'FizzBuzz',
 76,
 77,
 'Fizz',
 79,
 'Buzz',
 'Fizz',
 82,
 83,
 'Fizz',
 'Buzz',
 86,
 'Fizz',
 88,
 89,
 'FizzBuzz',
 91,
 92,
 'Fizz',
 94,
 'Buzz',
 'Fizz',
 97,
 98,
 'Fizz',
 'Buzz']

In [3]:
# specify the number of binary digits, variable so we can change it.
num_digits = 13

In [4]:
# Setup training data
raw_training_data = np.random.randint(101, 2**num_digits, 2**num_digits-100)
raw_training_data[:10]

array([ 696, 4939, 1165, 2094, 3099, 1613, 6276, 2386, 3633,  448])

In [5]:
# Setup the one hot encoding for fizzbuzz
def encode_fizz_buzz(x):
    '''
    1, 0, 0, 0 is fizzbuzz
    0, 1, 0, 0 is fizz
    0, 0, 1, 0 is buzz
    0, 0, 0, 1 is the number itself
    '''
    if x % 5 == 0 and x % 3 == 0:
        return np.array([1, 0, 0, 0])
    elif x % 3 == 0:
        return np.array([0, 1, 0, 0])
    elif x % 5 == 0:
        return np.array([0, 0, 1, 0])
    else:
        return np.array([0, 0, 0, 1])

In [6]:
def decode_fizz_buzz(i, one_hot_fizz_buzz):
    return ['fizzbuzz', 'fizz', 'buzz', str(i)][one_hot_fizz_buzz]

In [7]:
## Binary Encoding function
# In order to binary encode the input values
def binary_encode(i, NUM_DIGITS):
    return np.array([i >> d & 1 for d in range(NUM_DIGITS)])

In [8]:
encoded_training_data = [binary_encode(i, num_digits) for i in raw_training_data]
encoded_training_data[0:5]

[array([0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0]),
 array([1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1]),
 array([1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0]),
 array([0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0]),
 array([1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0])]

In [9]:
x_train = np.array(encoded_training_data)

In [10]:
y_train = np.array([encode_fizz_buzz(i) for i in raw_training_data])
y_train[0]

array([0, 1, 0, 0])

In [11]:
model = Sequential()

In [12]:
model.add(Dense(1000, input_dim=num_digits, activation="relu"))
model.add(Dense(1000, activation="relu"))
model.add(Dense(4, activation="softmax"))

In [13]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 1000)              14000     
_________________________________________________________________
dense_2 (Dense)              (None, 1000)              1001000   
_________________________________________________________________
dense_3 (Dense)              (None, 4)                 4004      
Total params: 1,019,004
Trainable params: 1,019,004
Non-trainable params: 0
_________________________________________________________________


In [14]:
model.compile(loss='categorical_crossentropy', optimizer='adagrad', metrics=["accuracy"])

In [15]:
model.fit(x_train, y_train, nb_epoch=30, batch_size=128)

Epoch 1/30
8092/8092 [==============================] - 1s 185us/step - loss: 1.2357 - accuracy: 0.5177
Epoch 2/30
8092/8092 [==============================] - 1s 112us/step - loss: 1.1308 - accuracy: 0.5284
Epoch 3/30
8092/8092 [==============================] - 1s 98us/step - loss: 1.1173 - accuracy: 0.5287
Epoch 4/30
8092/8092 [==============================] - 1s 100us/step - loss: 1.0938 - accuracy: 0.5313
Epoch 5/30
8092/8092 [==============================] - 1s 120us/step - loss: 1.0576 - accuracy: 0.5372
Epoch 6/30
8092/8092 [==============================] - 1s 96us/step - loss: 1.0021 - accuracy: 0.5568
Epoch 7/30
8092/8092 [==============================] - 1s 99us/step - loss: 0.9242 - accuracy: 0.6024
Epoch 8/30
8092/8092 [==============================] - 1s 99us/step - loss: 0.8221 - accuracy: 0.6697
Epoch 9/30
8092/8092 [==============================] - 1s 93us/step - loss: 0.6941 - accuracy: 0.7490
Epoch 10/30
8092/8092 [==============================] - 1s 93us/step

In [16]:
numbers = np.arange(1, 101)
x_test = np.transpose(binary_encode(numbers, num_digits))
x_test[:2]

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [17]:
y_test = model.predict_classes(x_test)

In [18]:
predictions = np.vectorize(decode_fizz_buzz)(numbers, y_test)

In [19]:
predictions

array(['1', '2', 'fizz', '4', 'buzz', 'fizz', '7', '8', 'fizz', 'buzz',
       '11', 'fizz', '13', '14', 'fizzbuzz', '16', '17', 'fizz', '19',
       'buzz', 'fizz', '22', '23', 'fizz', 'buzz', '26', 'fizz', '28',
       '29', 'fizzbuzz', '31', '32', 'fizz', '34', 'buzz', 'fizz', '37',
       '38', 'fizz', 'buzz', '41', 'fizz', '43', '44', 'fizzbuzz', '46',
       '47', 'fizz', '49', 'buzz', 'fizz', '52', '53', 'fizz', 'buzz',
       '56', 'fizz', '58', '59', 'fizzbuzz', '61', '62', 'fizz', '64',
       'buzz', 'fizz', '67', '68', 'fizz', 'buzz', '71', 'fizz', '73',
       '74', 'fizzbuzz', '76', '77', 'fizz', '79', 'buzz', 'fizz', '82',
       '83', 'fizz', 'buzz', '86', 'fizz', '88', '89', 'fizzbuzz', '91',
       '92', 'fizz', '94', 'buzz', 'fizz', '97', '98', 'fizz', 'buzz'],
      dtype='<U8')

In [20]:
answers = np.array([])
for i in numbers:
    if i % 15 == 0:
        answers = np.append(answers, "FizzBuzz")
    elif i % 5 == 0:
        answers = np.append(answers, "Buzz")
    elif i % 3 == 0:
        answers = np.append(answers, "Fizz")
    else:
        answers = np.append(answers, i)
answers

array(['1.0', '2.0', 'Fizz', '4', 'Buzz', 'Fizz', '7', '8', 'Fizz',
       'Buzz', '11', 'Fizz', '13', '14', 'FizzBuzz', '16', '17', 'Fizz',
       '19', 'Buzz', 'Fizz', '22', '23', 'Fizz', 'Buzz', '26', 'Fizz',
       '28', '29', 'FizzBuzz', '31', '32', 'Fizz', '34', 'Buzz', 'Fizz',
       '37', '38', 'Fizz', 'Buzz', '41', 'Fizz', '43', '44', 'FizzBuzz',
       '46', '47', 'Fizz', '49', 'Buzz', 'Fizz', '52', '53', 'Fizz',
       'Buzz', '56', 'Fizz', '58', '59', 'FizzBuzz', '61', '62', 'Fizz',
       '64', 'Buzz', 'Fizz', '67', '68', 'Fizz', 'Buzz', '71', 'Fizz',
       '73', '74', 'FizzBuzz', '76', '77', 'Fizz', '79', 'Buzz', 'Fizz',
       '82', '83', 'Fizz', 'Buzz', '86', 'Fizz', '88', '89', 'FizzBuzz',
       '91', '92', 'Fizz', '94', 'Buzz', 'Fizz', '97', '98', 'Fizz',
       'Buzz'], dtype='<U32')

In [21]:
evaluate = np.array(answers == predictions)
print(np.count_nonzero(evaluate == True) / 100)

0.51
